name: dinq_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  dio: ^5.7.0
  file_picker: ^8.1.7
  flutter_markdown: ^0.7.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.6.1
  intl: ^0.19.0
  lottie: ^3.1.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3
  toastification: ^1.0.0
  flutter_html: ^3.0.0-beta.2
  reorderable_grid: ^1.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/blogs/
    - assets/icons/
    - assets/icons/avatar/
    - assets/icons/line-icons/
    - assets/icons/search/
    - assets/icons/settings/
    - assets/icons/social-icons/
    - assets/icons/social-icons-line/
    - assets/images/
    - assets/images/analysis/
    - assets/images/card/
    - assets/images/landing/
    - assets/images/openings/
    - assets/images/widgets/
    - assets/logo/
    - assets/favicon.ico
  fonts:
    - family: Tomato Grotesk
      fonts:
        - asset: assets/fonts/tomato-grotesk/TomatoGrotesk-Regular.otf
          weight: 400
        - asset: assets/fonts/tomato-grotesk/TomatoGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/tomato-grotesk/TomatoGrotesk-SemiBold.otf
          weight: 600
    - family: UDC 1.04
      fonts:
        - asset: assets/fonts/UDC/udc1.04-mediun.otf
          weight: 500
        - asset: assets/fonts/UDC/udc1.04-bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
    - family: Editor Note
      fonts:
        - asset: assets/fonts/editor-note/EditorNote-Regular.otf
          weight: 400
        - asset: assets/fonts/editor-note/EditorNote-Medium.otf
          weight: 500
        - asset: assets/fonts/editor-note/EditorNote-Semibold.otf
          weight: 600
        - asset: assets/fonts/editor-note/EditorNote-Bold.otf
          weight: 700
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/clash-display/ClashDisplay-Semibold.ttf
          weight: 600
    - family: Geist
      fonts:
        - asset: assets/fonts/geist/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/geist/Geist-SemiBold.ttf
          weight: 600
